name: tests-orders

# What's the action trigger
on:
  pull_request
  
# Actions we want to do when a PR is created, re-open or updated
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
